import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";
import ServerHeader from "@/components/ServerHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
        <Suspense fallback={<div>Loading header...</div>}>
          <ServerHeader />
        </Suspense>

        {children}
      </body>
    </html>
  );
}
