import { IBaseCourier } from "@/interfaces/courier.interface";

const DUMMYCOURIERS: IBaseCourier[] = [
  {
    firstName: "Alice",
    lastName: "Smith",
    pid: 1001,
    phoneNumber: "+1234567890",
    email: "alice@example.com",
    password: "hashed_pw_1",
    profileImage: "https://example.com/alice.jpg",
    role: "courier",
    vehicle: "bicycle",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: true }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: ["req-001", "req-002"],
  },
  {
    firstName: "Bob",
    lastName: "Johnson",
    pid: 1002,
    phoneNumber: "+1987654321",
    email: "bob@example.com",
    password: "hashed_pw_2",
    profileImage: "https://example.com/bob.jpg",
    role: "courier",
    vehicle: "motorcycle",
    workingDays: {
      monday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "10:00", endHours: "18:00", booked: true }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: ["req-003"],
  },
  {
    firstName: "Charlie",
    lastName: "Lee",
    pid: 1003,
    phoneNumber: "+1122334455",
    email: "charlie@example.com",
    password: "hashed_pw_3",
    profileImage: "https://example.com/charlie.jpg",
    role: "courier",
    vehicle: "van",
    workingDays: {
      monday: [{ startHours: "12:00", endHours: "20:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    firstName: "Dana",
    lastName: "Martinez",
    pid: 1004,
    phoneNumber: "+1098765432",
    email: "dana@example.com",
    password: "hashed_pw_4",
    profileImage: "https://example.com/dana.jpg",
    role: "courier",
    vehicle: "car",
    workingDays: {
      monday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      tuesday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      wednesday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      thursday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      friday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      saturday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      sunday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
    },
    totalRequests: ["req-004", "req-005", "req-006"],
  },
  {
    firstName: "Ethan",
    lastName: "Nguyen",
    pid: 1005,
    phoneNumber: "+1222333444",
    email: "ethan@example.com",
    password: "hashed_pw_5",
    profileImage: "https://example.com/ethan.jpg",
    role: "courier",
    vehicle: "bicycle",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    firstName: "Fiona",
    lastName: "Garcia",
    pid: 1006,
    phoneNumber: "+1555666777",
    email: "fiona@example.com",
    password: "hashed_pw_6",
    profileImage: "https://example.com/fiona.jpg",
    role: "courier",
    vehicle: "scooter",
    workingDays: {
      monday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: ["req-007"],
  },
  {
    firstName: "George",
    lastName: "Brown",
    pid: 1007,
    phoneNumber: "+1444555666",
    email: "george@example.com",
    password: "hashed_pw_7",
    profileImage: "https://example.com/george.jpg",
    role: "courier",
    vehicle: "truck",
    workingDays: {
      monday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      tuesday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      wednesday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      thursday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      friday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      saturday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      sunday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
    },
    totalRequests: ["req-008", "req-009"],
  },
  {
    firstName: "Hannah",
    lastName: "Lopez",
    pid: 1008,
    phoneNumber: "+1333444555",
    email: "hannah@example.com",
    password: "hashed_pw_8",
    profileImage: "https://example.com/hannah.jpg",
    role: "courier",
    vehicle: "car",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      friday: [{ startHours: "12:00", endHours: "16:00", booked: true }],
      saturday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
    },
    totalRequests: ["req-010"],
  },
  {
    firstName: "Isaac",
    lastName: "Davis",
    pid: 1009,
    phoneNumber: "+1111222333",
    email: "isaac@example.com",
    password: "hashed_pw_9",
    profileImage: "https://example.com/isaac.jpg",
    role: "courier",
    vehicle: "van",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    firstName: "Jasmine",
    lastName: "White",
    pid: 1010,
    phoneNumber: "+1666777888",
    email: "jasmine@example.com",
    password: "hashed_pw_10",
    profileImage: "https://example.com/jasmine.jpg",
    role: "courier",
    vehicle: "electric scooter",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
];

export default DUMMYCOURIERS;
