import { ICourier } from "@/app/_interfaces/courier.interface";

const DUMMYCOURIERS: ICourier[] = [
  {
    _uuid: "uuid-001",
    _created: 1713800000,
    _modified: 1713900000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-001",
    _user: "user_001",
    firstName: "Alice",
    lastName: "Smith",
    pid: 1001,
    phoneNumber: "+1234567890",
    email: "alice@example.com",
    password: "hashed_pw_1",
    profileImage: "https://example.com/alice.jpg",
    role: "courier",
    vehicle: "bicycle",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: true }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [],
    },
    totalRequests: ["req-001", "req-002"],
  },
  {
    _uuid: "uuid-002",
    _created: 1713801000,
    _modified: 1713901000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-002",
    _user: "user_002",
    firstName: "Bob",
    lastName: "Johnson",
    pid: 1002,
    phoneNumber: "+1987654321",
    email: "bob@example.com",
    password: "hashed_pw_2",
    profileImage: "https://example.com/bob.jpg",
    role: "courier",
    vehicle: "motorcycle",
    workingDays: {
      monday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "10:00", endHours: "18:00", booked: true }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: ["req-003"],
  },
  {
    _uuid: "uuid-003",
    _created: 1713802000,
    _modified: 1713902000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-003",
    _user: "user_003",
    firstName: "Charlie",
    lastName: "Lee",
    pid: 1003,
    phoneNumber: "+1122334455",
    email: "charlie@example.com",
    password: "hashed_pw_3",
    profileImage: "https://example.com/charlie.jpg",
    role: "courier",
    vehicle: "van",
    workingDays: {
      monday: [{ startHours: "12:00", endHours: "20:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    _uuid: "uuid-004",
    _created: 1713803000,
    _modified: 1713903000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-004",
    _user: "user_004",
    firstName: "Dana",
    lastName: "Martinez",
    pid: 1004,
    phoneNumber: "+1098765432",
    email: "dana@example.com",
    password: "hashed_pw_4",
    profileImage: "https://example.com/dana.jpg",
    role: "courier",
    vehicle: "car",
    workingDays: {
      monday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      tuesday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      wednesday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      thursday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      friday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      saturday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
      sunday: [{ startHours: "07:00", endHours: "15:00", booked: true }],
    },
    totalRequests: ["req-004", "req-005", "req-006"],
  },
  {
    _uuid: "uuid-005",
    _created: 1713804000,
    _modified: 1713904000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-005",
    _user: "user_005",
    firstName: "Ethan",
    lastName: "Nguyen",
    pid: 1005,
    phoneNumber: "+1222333444",
    email: "ethan@example.com",
    password: "hashed_pw_5",
    profileImage: "https://example.com/ethan.jpg",
    role: "courier",
    vehicle: "bicycle",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    _uuid: "uuid-006",
    _created: 1713805000,
    _modified: 1713905000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-006",
    _user: "user_006",
    firstName: "Fiona",
    lastName: "Garcia",
    pid: 1006,
    phoneNumber: "+1555666777",
    email: "fiona@example.com",
    password: "hashed_pw_6",
    profileImage: "https://example.com/fiona.jpg",
    role: "courier",
    vehicle: "scooter",
    workingDays: {
      monday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      tuesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      wednesday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      thursday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      friday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      saturday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
      sunday: [{ startHours: "09:00", endHours: "17:00", booked: false }],
    },
    totalRequests: ["req-007"],
  },
  {
    _uuid: "uuid-007",
    _created: 1713806000,
    _modified: 1713906000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-007",
    _user: "user_007",
    firstName: "George",
    lastName: "Brown",
    pid: 1007,
    phoneNumber: "+1444555666",
    email: "george@example.com",
    password: "hashed_pw_7",
    profileImage: "https://example.com/george.jpg",
    role: "courier",
    vehicle: "truck",
    workingDays: {
      monday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      tuesday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      wednesday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      thursday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      friday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      saturday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
      sunday: [{ startHours: "10:00", endHours: "18:00", booked: false }],
    },
    totalRequests: ["req-008", "req-009"],
  },
  {
    _uuid: "uuid-008",
    _created: 1713807000,
    _modified: 1713907000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-008",
    _user: "user_008",
    firstName: "Hannah",
    lastName: "Lopez",
    pid: 1008,
    phoneNumber: "+1333444555",
    email: "hannah@example.com",
    password: "hashed_pw_8",
    profileImage: "https://example.com/hannah.jpg",
    role: "courier",
    vehicle: "car",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      friday: [{ startHours: "12:00", endHours: "16:00", booked: true }],
      saturday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "12:00", booked: false }],
    },
    totalRequests: ["req-010"],
  },
  {
    _uuid: "uuid-009",
    _created: 1713808000,
    _modified: 1713908000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-009",
    _user: "user_009",
    firstName: "Isaac",
    lastName: "Davis",
    pid: 1009,
    phoneNumber: "+1111222333",
    email: "isaac@example.com",
    password: "hashed_pw_9",
    profileImage: "https://example.com/isaac.jpg",
    role: "courier",
    vehicle: "van",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
  {
    _uuid: "uuid-010",
    _created: 1713809000,
    _modified: 1713909000,
    _data_type: "courier",
    _is_deleted: false,
    _self_link: "/couriers/uuid-010",
    _user: "user_010",
    firstName: "Jasmine",
    lastName: "White",
    pid: 1010,
    phoneNumber: "+1666777888",
    email: "jasmine@example.com",
    password: "hashed_pw_10",
    profileImage: "https://example.com/jasmine.jpg",
    role: "courier",
    vehicle: "electric scooter",
    workingDays: {
      monday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      tuesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      wednesday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      thursday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      friday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      saturday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
      sunday: [{ startHours: "08:00", endHours: "16:00", booked: false }],
    },
    totalRequests: [],
  },
];

export default DUMMYCOURIERS;
